apiVersion: apps/v1
kind: Deployment
metadata:
  name: epa-controller
  namespace: epa-system
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-epa-agent-0
      containers:
        - name: controller
          image: docker.io/rust:latest
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/app
          command:
            - sleep
            - infinity
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - containerPort: 8443
              name: webhook
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: app
              mountPath: /usr/src/app
              readOnly: false
            - name: cargo-cache
              mountPath: /usr/local/cargo/registry
            - name: target-cache
              mountPath: /usr/src/app/target
      volumes:
        - name: app
          hostPath:
            path: /app
        - name: cargo-cache
          emptyDir: {}
        - name: target-cache
          emptyDir: {}
