apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ctx.sh/authors: "EPA Authors"
  ctx.sh/license: "Apache"
resources:
  - ../../base
  - dummy-metrics.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: epa-controller
      namespace: epa-system
