apiVersion: v1
kind: Service
metadata:
  name: {{ include "epa.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "epa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "epa.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: 8443
      {{- if .Values.service.webhookNodePort }}
      nodePort: {{ .Values.service.webhookNodePort }}
      {{- end }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 9090
      protocol: TCP
