---
apiVersion: v1
kind: Service
metadata:
  name: epa-webhook
  namespace: epa-system
  labels:
    app: epa-controller
spec:
  type: NodePort
  selector:
    app: epa-controller
  ports:
    - name: webhook
      port: 443
      targetPort: 8443
      nodePort: 30443
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
